// ============================================================
// Sale360 — Import Configurations
// ============================================================
import type { ImportConfig, ImportType } from './import-types';

export const IMPORT_CONFIGS: Record<ImportType, ImportConfig> = {
  variationTemplates: {
    type: 'variationTemplates',
    title: 'Templates de Variação',
    endpoint: 'variation-templates/import',
    templateFilename: 'import_templates_variacao.csv',
    templateLabel: 'Baixar template de variações',
    sequenceNumber: 1,
    dependencies: [],
    expectedColumns: ['Nome do Template', 'Dim 1 - Tipo', 'Dim 1 - Rótulo', 'Dim 1 - Opções', 'Dim 2 - Tipo', 'Dim 2 - Rótulo', 'Dim 2 - Opções'],
    description: 'Templates de variação',
    longDescription: 'Define templates com dimensões de variação (ex: Tamanho + Cor para roupas). Só importe se sua loja trabalha com produtos que variam.',
  },
  categories: {
    type: 'categories',
    title: 'Categorias',
    endpoint: 'categories/import',
    templateFilename: 'import_categorias.csv',
    templateLabel: 'Baixar template de categorias',
    sequenceNumber: 2,
    dependencies: ['variationTemplates'],
    expectedColumns: ['Nome', 'Cor (hex)', 'Ordem', 'Template de Variação'],
    description: 'Categorias',
    longDescription: 'Categorias organizam seus produtos no catálogo. Se tiver templates de variação, vincule aqui.',
  },
  suppliers: {
    type: 'suppliers',
    title: 'Fornecedores',
    endpoint: 'suppliers/import',
    templateFilename: 'import_fornecedores.csv',
    templateLabel: 'Baixar template de fornecedores',
    sequenceNumber: 3,
    dependencies: [],
    expectedColumns: ['Nome', 'CNPJ', 'IE', 'Email', 'Telefone', 'WhatsApp', 'Contato', 'Endereço', 'Número', 'Complemento', 'Bairro', 'Cidade', 'Estado', 'CEP', 'Observações', 'Ativo'],
    description: 'Fornecedores',
    longDescription: 'Fornecedores são necessários para registrar compras e rastrear lotes de estoque.',
  },
  products: {
    type: 'products',
    title: 'Produtos Simples',
    endpoint: 'products/import',
    templateFilename: 'import_produtos.csv',
    templateLabel: 'Baixar template de produtos',
    sequenceNumber: 4,
    dependencies: ['categories'],
    expectedColumns: ['Nome', 'Descrição', 'SKU', 'Código de Barras', 'Categoria', 'Preço de Venda', 'Custo Unitário', 'Custo Operacional', 'Taxa (%)', 'Estoque Inicial', 'Estoque Mínimo', 'Unidade', 'Ativo', 'Fracionado'],
    description: 'Produtos simples (sem variação)',
    longDescription: 'Importe produtos simples (sem variações). Para produtos com variações (roupas, calçados), use o template de Produtos com Variações.',
  },
  productsVariations: {
    type: 'productsVariations',
    title: 'Produtos com Variações',
    endpoint: 'products/import',
    templateFilename: 'import_produtos_variacoes.csv',
    templateLabel: 'Baixar template de produtos com variações',
    sequenceNumber: 4,
    dependencies: ['variationTemplates', 'categories'],
    expectedColumns: ['Nome do Produto', 'Categoria', 'Preço Base', 'Tamanho', 'Cor', 'Qtd', 'Preço Extra', 'SKU', 'Código de Barras', 'Estoque Mínimo'],
    description: 'Produtos com variações',
    longDescription: 'Cada linha = uma variação do produto. Linhas com mesmo Nome do Produto são agrupadas automaticamente.',
  },
  purchases: {
    type: 'purchases',
    title: 'Compras',
    endpoint: 'purchases/import',
    templateFilename: 'import_compras.csv',
    templateLabel: 'Baixar template de compras',
    sequenceNumber: 5,
    dependencies: ['suppliers', 'products'],
    expectedColumns: ['Nº Pedido', 'Fornecedor', 'Produto', 'Variação', 'Quantidade', 'Custo Unitário', 'Preço de Venda', 'Data Recebimento', 'Status', 'Observação'],
    description: 'Compras com lotes de estoque',
    longDescription: '⭐ Etapa mais importante! Gera lotes de estoque (PEPS/FIFO), movimentações e atualiza o estoque dos produtos. Use status RECEIVED para dar entrada.',
  },
};
